### PR TITLE
Add scroll bars

### PR DESCRIPTION
**Pull request by BraisGabin**
I will rebase this branch more than once. Be carefull if you merge this PR.

Remaining tasks:
- [x] Update README minSdkVersion = 5
- [ ] Enable scrollbars only if they are needed.
- [ ] ScrollBar inside the content. Image 1
- [ ] Overlap the scrollbars. Image 2

device-2013-10-20-000321

device-2013-10-20-000306

### CODE REVIEW

**Comment by kuldeepdhaka** [comment]
Works for me. Tested on Android 5.0.2 (Lollipop) MotoG

**Comment by kuldeepdhaka** [comment]
tip: update version of this PR (against master) 
https://github.com/kuldeepdhaka/TableFixHeaders/tree/scroll-bar
NOTE: this also contain fix for Android 5 (see previous comment url)

**Comment by BryanJBryce** [comment]
Is project dead? This should have been merged in awhile ago right?

**Comment by BraisGabin** [comment]
Merged! And yes, the project is more less dead. I don't have time to improve this project. It needs a huge refactor to add some FR like #39 or #52. Unfortunately, this project project is not one of my priorities right now.

**Pull request merged**
